spring:
  datasource:
    url: jdbc:mysql://10.86.65.20:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: UAT@2018
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      one:
        username: root
        password: UAT@2018
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.86.65.20:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        initialSize: 5
        minIdle: 5
        maxActive: 20
        initial-size: 3
        min-idle: 3
        max-active: 10
        max-wait: 60000
      two:
        username: sa
        password: Hello1234
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://127.0.0.1:1433;databaseName=AdomdConfigDB
        initialSize: 5
        minIdle: 5
        maxActive: 20
        initial-size: 6
        min-idle: 6
        max-active: 20
        max-wait: 12000
#      initial-size: 5 #连接池初始化大小
#      min-idle: 10 #最小空闲连接数
#      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  path: /var/logs #配置日志生成路径